// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBengdxGNEAXhua-kc_tBKOzkp4ER-QLm8',
    appId: '1:234858094944:web:dafebad75fd12f93827e05',
    messagingSenderId: '234858094944',
    projectId: 'myhirexxo',
    authDomain: 'myhirexxo.firebaseapp.com',
    storageBucket: 'myhirexxo.appspot.com',
    measurementId: 'G-6B0509ZQ6Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByKKQto3cuWTjU4u5mGUERZhqT_jYMWgg',
    appId: '1:234858094944:android:000be5fcac4d1073827e05',
    messagingSenderId: '234858094944',
    projectId: 'myhirexxo',
    storageBucket: 'myhirexxo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCt2ET0XTYuBUpq2H1uUJO5cgQcaH4DtAo',
    appId: '1:234858094944:ios:01898a22aaedb0d3827e05',
    messagingSenderId: '234858094944',
    projectId: 'myhirexxo',
    storageBucket: 'myhirexxo.appspot.com',
    androidClientId: '234858094944-il444hc71mm07dso3tjc6448j7o2rj7v.apps.googleusercontent.com',
    iosBundleId: 'com.example.todolist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCt2ET0XTYuBUpq2H1uUJO5cgQcaH4DtAo',
    appId: '1:234858094944:ios:008ce601d77216d8827e05',
    messagingSenderId: '234858094944',
    projectId: 'myhirexxo',
    storageBucket: 'myhirexxo.appspot.com',
    androidClientId: '234858094944-il444hc71mm07dso3tjc6448j7o2rj7v.apps.googleusercontent.com',
    iosBundleId: 'com.example.todolist.RunnerTests',
  );
}
